export const ADD_TASK = 'ADD_TASK';
export const ADD_TASK_BEGIN = 'ADD_TASK_BEGIN'
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_FAILURE = 'ADD_TASK_FAILURE';

export const DELETE_TASK = 'DELETE_TAKS';
export const DELETE_TASK_BEGIN = 'DELETE_TASK_BEGIN'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILURE = 'DELETE_TASK_SUCCESS';

export const COMPLETE_TASK = 'COMPLETE_TASK';
export const COMPLETE_TASK_BEGIN = 'COMPLETE_TASK_BEGIN'
export const COMPLETE_TASK_SUCCESS = 'COMPLETE_TASK_SUCCESS';
export const COMPLETE_TASK_FAILURE = 'COMPLETE_TASK_FAILURE';

export const GET_TASKS = 'GET_TASKS';
export const GET_TASKS_BEGIN = 'GET_TASKS_BEGIN'
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_FAILURE = 'GET_TASKS_FAILURE';

